Algoritmo "Operadores Aritmeticos"
// 
//  
// Descrição   : operadores matematicos
// Autor(a)    : Andrelino Roberto de Faria
// Data atual  : 09/07/2020
Var
// Seção de Declarações das variáveis 
   resultado, valor1, valor2, valor3: real
   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor1 :=10
   valor2 :=10
   valor3 :=10
   resultado := ((valor1 + valor2 + valor2) / valor3) %2
   escreval ("Resultado: ", resultado)


Fimalgoritmo