Algoritmo "variaveis"
// 
//  
// Descrição   : Aula sobre variaveis
// Autor(a)    : Andrelino Roberto de Faria
// Data atual  : 05/05/2020
Var
// Seção de Declarações das variáveis 
// Como Declarar variaveis
// primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome, cidade, endereco: caractere
          idade: inteiro
          

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo